import { pool } from '../config/database';

export interface ILicense {
    key?: string; // Optional on creation, generated by controller
    firstName: string;
    lastName: string;
    idNumber: string;
    businessName: string;
    sector: string;
    status: 'active' | 'expired' | 'revoked';
    expirationDate: Date;
    software: 'rutadata' | 'other';
    userId?: number;
}

export class LicenseModel {
    private static mapRowToLicense(row: any): ILicense {
        return {
            key: row.key,
            firstName: row.first_name,
            lastName: row.last_name,
            idNumber: row.id_number,
            businessName: row.business_name,
            sector: row.sector,
            status: row.status as any,
            expirationDate: new Date(row.expiration_date),
            software: row.software as any,
            userId: row.user_id 
        };
    }

    static async findByKey(key: string): Promise<ILicense | undefined> {
        const result = await pool.query('SELECT * FROM licenses WHERE key = $1', [key]);
        if (result.rows.length === 0) return undefined;
        return this.mapRowToLicense(result.rows[0]);
    }

    static async create(license: ILicense): Promise<ILicense> {
        await pool.query(
            'INSERT INTO licenses (key, first_name, last_name, id_number, business_name, sector, software, status, expiration_date, user_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)',
            [license.key, license.firstName, license.lastName, license.idNumber, license.businessName, license.sector, license.software, license.status, license.expirationDate, license.userId || null]
        );
        return license;
    }

    static async getAll(): Promise<ILicense[]> {
        const result = await pool.query('SELECT * FROM licenses ORDER BY created_at DESC');
        return result.rows.map(this.mapRowToLicense);
    }
    
    static async getAllByUser(userId: number): Promise<ILicense[]> {
        const result = await pool.query('SELECT * FROM licenses WHERE user_id = $1 ORDER BY created_at DESC', [userId]);
        return result.rows.map(this.mapRowToLicense);
    }

    static async updateStatus(key: string, status: string): Promise<ILicense | undefined> {
        const result = await pool.query(
            'UPDATE licenses SET status = $1 WHERE key = $2 RETURNING *',
            [status, key]
        );
        if (result.rows.length === 0) return undefined;
        return this.mapRowToLicense(result.rows[0]);
    }

    static async delete(key: string): Promise<boolean> {
        const result = await pool.query('DELETE FROM licenses WHERE key = $1', [key]);
        return (result.rowCount ?? 0) > 0;
    }
}
